
<div class="sidebar-clock">
  <svg>
    <text  text-anchor="middle" x="50%" y="80%" class="words words-1"></text>
    <text  text-anchor="middle" x="50%" y="80%" class="words words-2"></text>
    <text  text-anchor="middle" x="50%" y="80%" class="words words-3"></text>
    <text  text-anchor="middle" x="50%" y="80%" class="words words-4"></text>
  </svg>
</div>
<script src="/blog/js/src/sidebar-clock.js"></script>
